[package]
name = "siders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kommand = "0"
nameless = "0"
nom = "7.1.0"